apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.22.0 (955b78124)
  creationTimestamp: null
  labels:
    io.kompose.service: databaseservice
  name: databaseservice
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: databaseservice
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.22.0 (955b78124)
      creationTimestamp: null
      labels:
        io.kompose.service: databaseservice
    spec:
      containers:
        - args:
            - --default-authentication-plugin=mysql_native_password
          env:
            - name: MYSQL_DATABASE
              value: demo_cloud_web_service
            - name: MYSQL_ROOT_PASSWORD
              value: example
          image: mysql
          name: databaseservice
          ports:
            - containerPort: 3306
          resources: {}
      restartPolicy: Always
status: {}
