# Use root/example as user/password credentials
version: "3.1"

services:
  frontend:
    image: ludesdeveloper/demo_cloud_web_service_frontend:latest
    restart: always
    ports:
      - 3000:3000
  backendgolang:
    image: ludesdeveloper/demo_cloud_web_service_backend_golang:latest
    restart: always
    ports:
      - 1323:1323
  databaseservice:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: demo_cloud_web_service
    ports:
      - 3306:3306
  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080
